# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="wezm-duke"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git web-search docker docker-compose)

zstyle ':omz:alpha:lib:git' async-prompt no
source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"


# !!!!!! PERSONAL SHIT !!!!!! probably breaking something

# NOTE: edit the true dotfiles, not symlinks or copies
export DOTFILES="$HOME/.everc/dotfiles"
export DOTPROFILE="rogue"
alias dot="cd $DOTFILES && code ."
alias dots_refresh='dot && ./installDotfiles.sh --profile $DOTPROFILE && source ~/.zshrc && popd'
alias vz="vim $DOTFILES/profiles/rogue/home/zshrc"

# Load secrets (API keys, tokens, etc.) - stored in $DOTFILES/secrets/
[[ -f "$DOTFILES/profiles/shared/home/secrets.sh" ]] && source "$DOTFILES/profiles/shared/home/secrets.sh"

# mmmmm sexy colors, https://github.com/trapd00r/LS_COLORS#installation
source "$HOME/bin/lscolors.sh"

# # ******************************************************************
# # reboot directly to windows
# #   Inspired by http://askubuntu.com/questions/18170/how-to-reboot-into-windows-from-ubuntu
# # ******************************************************************
# function rebootwindows() {
#     WINDOWS_TITLE=`grep -i "^menuentry 'Windows" /boot/grub/grub.cfg|head -n 1|cut -d"'" -f2`
#     sudo grub-reboot "$WINDOWS_TITLE"
#     sudo reboot
#     echo $WINDOWS_TITLE
# }

# ENV config
export EDITOR='/usr/bin/code'
export ROGUE_ROOT="/home/adam/rogue"
export ROGUE_BUILDS="$ROGUE_ROOT/builds"
export MAV_SRC="$ROGUE_ROOT/src/maverick"
export MAV_DEBUG="$ROGUE_ROOT/builds/debug"
export PATH=$PATH:$ROGUE_ROOT/builds/mav_tools/animation_maker/cram
export PATH=$PATH:$HOME/.local/bin

# QoL
alias elite="cd $MAV_SRC/elite"
alias plat="cd $MAV_SRC/platinum"
alias encore="cd $MAV_SRC/encore"

alias c="clear"
alias o='mimeopen'
alias t='xfce4-terminal'
alias chrome='google-chrome'
alias py='python3'
alias python='python3'
alias pip='pip3'
alias ypic='xclip -selection clipboard  -t image/png -i'
alias audacity="$HOME/bin/audacity-linux-3.1.3-x86_64.AppImage &"
alias ssh-lurch='ssh lurch@raspberrypi.local'
alias tbg="source $HOME/bin/toggleBG"
alias sdi="sudo dpkg -i"

# git
alias gs="git status"
alias gac="git commit -am"


# nodejs and npm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
